version: '3.8'
services:
  db:
    image: postgres:13
    container_name: domains_postpg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./app
    container_name: domains_postpg_web
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: